apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nginx-sample
  annotations:
    backstage.io/kubernetes-id: nginx-sample
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
